name: Update Project Layout

on:
  push:
    branches: [main]

jobs:
  manipulate-file:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Run generate-structure script
        run: |
          node ./scripts/generate-structure.mjs

      - name: Commit and Push layout to README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update README.md [skip CI]"
